### ISSUE TITLE
AmazonMQ - AmazonMQ Configuration yml Is Missing From Namespaces List

### ISSUE THREAD

**Issue by daniel-tk** [logzio/logzio-aws-metrics#10]

**Comment by yotamloe** [comment]
Can you please elaborate on that?

**Comment by daniel-tk** [comment]
In our docs, on the shipping page, we have an AmazonMQ page, so as a user I assume our aws integration works with this service.
Correct me if I'm wrong but all supported aws services has their configuration file in the cw_namespaces folder, containing the scraped metrics and dimensions.
I wanted to examine the AmazonMQ scraped metrics and dimensions, but don't see this service configuration file in cw_namespaces.
