### ISSUE TITLE
Application ELB - Irelevant Dimensions

### ISSUE THREAD

**Issue by daniel-tk** [logzio/logzio-aws-metrics#13]
All metrics in the configuration yml look for the dimensions `LoadBalancer` and `TargetGroup`, even though some of the metrics only have the `LoadBalancer` dimension. 
This might cause confusion, and maybe also scraping issues?

**Comment by yotamloe** [comment]
What metrics only have the `LoadBalancer ` dimension?
And about the scrapping issue: can you see a difference between the metrics in cloudwatch to the metrics in the metrics-account? can you list them?

**Comment by daniel-tk** [comment]
Well no ApplicationELB metrics arrive to our Logzio account so can't tell the difference...This is what I meant in scraping issue - perhaps they are not being scraped at all because of the interval, like in S3?

List of metrics with only `LoadBalancer` (according to aws doc - https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html): 

- `ActiveConnectionCount `
- `NewConnectionCount `
- `RejectedConnectionCount `
- `IPv6RequestCount `
- `NonStickyRequestCount `
- `HTTPCode_ELB_3XX_Count `
- `HTTPCode_ELB_4XX_Count `
- `HTTPCode_ELB_5XX_Count `
- `ProcessedBytes `
- `IPv6ProcessedBytes `
- `ConsumedLCUs `
- `ClientTLSNegotiationErrorCount `
- `RuleEvaluations `
