### ISSUE TITLE
Global - Don't See P8S_LOGZIO_NAME Label 

### ISSUE THREAD

**Issue by daniel-tk** [logzio/logzio-aws-metrics#5]
I started to ship AWS metrics with the following configuration:

`AWS_ACCESS_KEY_ID=***** 
AWS_SECRET_ACCESS_KEY=****** 
AWS_DEFAULT_REGION=us-east-1 LOGZIO_REGION=us 
LOGZIO_TOKEN=***** AWS_NAMESPACES=AWS/EC2,AWS/DynamoDB,CWAgent,AWS/ECS,AWS/ELB,AWS/ApplicationELB,AWS/GatewayELB,AWS/NetworkELB,AWS/Kinesis,AWS/Lambda,AWS/RDS,AWS/Route53,AWS/S3,AWS/SQS,AWS/SNS 
SCRAPE_INTERVAL=300 
P8S_LOGZIO_NAME=DanielAWS`

But in Grafana, when querying the metrics, I don't see the label  P8S_LOGZIO_NAME

**Comment by yotamloe** [comment]
Should work now with the new PR #16 Just make sure you update the image version.

**Comment by daniel-tk** [comment]
Very weird, I only see the p9s label in the logzio account when querying very specific aws metrics `(aws_ec2_network_out_average)`, and even then the label shows for sone ec2 instances, and for some it doesn't.
In other aws services metrics I don't see the label at all.
I re-downloaded the docker-compose file from the main repository page, pergaps I missed something? 

![image](https://user-images.githubusercontent.com/55798673/110469490-63c8cb80-80e2-11eb-9ca3-9e9b3f1434fd.png)

**Comment by yotamloe** [comment]
You need to update the logzio/config-builder image, not the docker-compose. just delete the image and then run the docker-compose again it will pull the new version.
